Upgrade to  bdk ffi v0.30.0
LtbLightning/bdk-rn pull request #72
Opened 2024-01-12 18:35 UTC by BitcoinZavior

2024-01-18 12:06 UTC, Czino approved these changes
I was concerned at first that moving every function in a separate thread would break functionality (I vaguely remember something breaking, when I tried that)
However, after compiling the update and checking through every bit of functionality we use at Peach, I can confirm that all keeps working well on Android and iOS 👌

2024-01-18 14:44 UTC, Czino requested changes

2024-01-21 01:12 UTC, BitcoinZavior commented on ios/BdkRnModule.swift
> +        DispatchQueue.main.async { [self] in
Interestingly, the change in the PR was meant to avoid UI thread blocking.
Will check your PR and this once again

2024-01-25 12:08 UTC, Czino commented
Unfortunately after the last commit, my app keeps crashing right at startup.

2024-01-29 09:46 UTC, Czino commented
This is another issue caused by the upgrade: https://github.com/LtbLightning/bdk-rn/issues/75

2024-01-30 00:10 UTC, BitcoinZavior commented
> Unfortunately after the last commit, my app keeps crashing right at startup.
Hi @Czino 
Not able to replicate.
The demo app is updated to use the latest commit: https://github.com/LtbLightning/bdk-rn-demo
(Be sure to point bdk-rn to local path in package json)
Are you able to run the app? or does that crash too?

2024-01-30 09:15 UTC, Czino commented
Unfortunately the demo does not run at all for me
<img width="282" alt="image" src="https://github.com/LtbLightning/bdk-rn/assets/42438775/5d8606a9-3531-4da8-9f0f-1abb1b446607">

Looks like some extra steps are needed to make it run on my machine.

2024-02-19 09:51 UTC, Czino commented on android/src/main/java/io/ltbl/bdkrn/BdkRnModule.kt
> +                val addressInfo = getWalletById(id).getAddress(setAddressIndex(resolvedIndex))
Is this change on purpose? The ios/BdkRnModule.swift remains unchanged for this method.

2025-03-20 00:21 UTC, merged